[project]
name = "kaskade"
dynamic = ["version"]
description = "kaskade is a text user interface for kafka"
authors = [{ name = "Saúl Piña", email = "sauljabin@gmail.com" }]
license = "MIT"
readme = "README.md"
keywords = ["kafka", "kaskade"]
classifiers = [
    "Environment :: Console",
    "Operating System :: MacOS",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
requires-python = ">=3.10,<3.15"
dependencies = [
    "cloup>=3.1",
    "fastavro>=1.12",
    "textual>=8.2",
    "confluent-kafka[avro,json,protobuf]>=2.15",
    "pyyaml>=6.0",
]

[project.scripts]
kaskade = "kaskade.main:cli"

[project.urls]
homepage = "https://github.com/sauljabin/kaskade"
repository = "https://github.com/sauljabin/kaskade"
documentation = "https://github.com/sauljabin/kaskade"
changelog = "https://github.com/sauljabin/kaskade/releases"
issues = "https://github.com/sauljabin/kaskade/issues"
funding = "https://github.com/sponsors/sauljabin"

[dependency-groups]
dev = [
    "actionlint-py",
    "black",
    "faker",
    "mypy",
    "pre-commit",
    "ruff",
    "testcontainers",
    "textual-dev",
    "types-attrs",
    "types-protobuf",
    "types-pyyaml",
    "typos",
]

[build-system]
requires = ["hatchling>=1.27,<2", "hatch-vcs>=0.5,<1"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
tag-pattern = "^v(?P<version>[0-9]+\\.[0-9]+\\.[0-9]+)$"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"

[tool.hatch.build.targets.wheel]
packages = ["kaskade"]

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = ["C901"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.typos]
type.lock.extend-glob = ["*.lock"]
type.lock.check-file = true
files.extend-exclude = ["uv.lock"]
